Подключен java-artifact-publish-plugin
yoomoney-gradle-plugins/artifact-release-plugin pull request #13
Opened 2021-02-25 18:26 UTC by layfe

2021-02-25 18:35 UTC, layfe commented on build.gradle
> +    tasks.getByName("publishPluginMavenPublicationToMavenRepository").enabled(false)
здесь проблема - внешний плагин по публикации плагинов в Plugin Portal создает публикацию PluginMaven, и таска публикации пытается опубликовать полученный артефакт. Публиковать его в maven нам не нужно.
Думала использовать для публикации четкое имя таски (publishMainArtifactPublicationToMavenRepository), но не получилось - таска поздно создается (внешним плагином) и мы ее не видим, когда хотим повесить dependsOn при обработке releaseSettings.releaseTasks.

В итоге делаю disable. 
Может есть идеи, как сделать лучше?

2021-02-26 07:11 UTC, f0y requested changes

2021-02-26 07:11 UTC, f0y commented on build.gradle
> +    snapshotRepository = "https://oss.sonatype.org/content/repositories/snapshots/"
Какие условия хранения снапшотов?

2021-02-26 07:11 UTC, f0y commented on build.gradle
> +    tasks.getByName("publishPluginMavenPublicationToMavenRepository").enabled(false)
Ты про это?  project.getExtensions().getByType(GradlePluginDevelopmentExtension.class).setAutomatedPublishing(false);

2021-02-26 07:11 UTC, f0y commented on build.gradle
> -    pkg {
А где вся эта инфа для maven будет задаваться?

2021-02-26 14:19 UTC, layfe commented on build.gradle
> +    snapshotRepository = "https://oss.sonatype.org/content/repositories/snapshots/"
по длительности?
про cleanup джобу нашла такую инфу:
The job runs twice a week, and it has a minimum snapshot count of 4 with snapshot retention of 2 days.

2021-03-01 14:33 UTC, layfe commented
добавила в java-artifact-publish-plugin возможность добавлять настройки для pom файла.

2021-03-01 14:38 UTC, f0y requested changes

2021-03-01 14:38 UTC, f0y commented on build.gradle
> +        description = "Gradle artifact release plugin"
Описание не то

2021-03-01 14:38 UTC, f0y commented on build.gradle
> +                organizationUrl = 'https://yoomoney.ru'
мы сможем на уровне project плагина указать организацию?

2021-03-01 14:38 UTC, f0y commented on build.gradle
> +                organization = 'Yoomoney'
```suggestion
                organization = 'YooMoney'
```

2021-03-01 14:58 UTC, layfe commented on build.gradle
> +        description = "Gradle artifact release plugin"
почему? как было, Gradle artifact release plugin, вроде ок? мы в релизном плагине

2021-03-01 14:59 UTC, layfe commented on build.gradle
> +                organizationUrl = 'https://yoomoney.ru'
да, все эти настройки кроме description планирую задавать из project-plugin

2021-03-01 14:59 UTC, f0y commented on build.gradle
> +        description = "Gradle artifact release plugin"
Ошибся

2021-03-01 18:35 UTC, layfe commented on build.gradle
> -    pkg {
сделала настройки для информации pom

2021-03-02 05:54 UTC, f0y approved these changes

2021-03-02 15:26 UTC, merged