Добавлена проверка на то, что присутствует секция **breaking changes* при мажорном обновлении плагина.
yoomoney-gradle-plugins/artifact-release-plugin pull request #15
Opened 2021-03-25 16:12 UTC by poisonedvk

2021-03-25 16:30 UTC, layfe requested changes
NW до прояснения момента про тестирование на каком нибудь проекте - надо проверить, что сборка корректно проходит и корректно падает

2021-03-25 16:30 UTC, layfe commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/changelog/CheckChangeLogTask.kt
> +                    "Пример оформления см. в README.MD. ")
когда в логах сборках либы будет написано "см в READ.MD" - будет непонятно, в каком имено read.me.
можно либо объяснить, либо ссылку добаить

2021-03-25 16:30 UTC, layfe commented on src/test/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManagerTest.kt
> +        Assert.assertTrue("В changelogs при мажорном обновлении должно быть описание **breaking changes**",
в этом сообщение лучше написать что то типа "Не нашли breakingChanges, а должны были."
потому что такой комментарий, как мне кажется, не проясняет, почему упал тест

2021-03-25 16:30 UTC, layfe commented on src/test/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManagerTest.kt
> +        Assert.assertFalse("В changelogs при мажорном обновлении должно быть описание **breaking changes**",
и здесь

2021-03-25 16:30 UTC, layfe commented on src/test/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManagerTest.kt
> +    @Test
возможно стоит добавить более общий тест, проверяющий, что сборка проекта падает в случае MAJOR + отсутствие  breaking changes.

Функциональность протестирована на каком нибудь проекте?

2021-03-25 17:11 UTC, poisonedvk commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/changelog/CheckChangeLogTask.kt
> +                    "Пример оформления см. в README.MD. ")
Добавил ссылку

2021-03-25 17:12 UTC, poisonedvk commented on src/test/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManagerTest.kt
> +        Assert.assertTrue("В changelogs при мажорном обновлении должно быть описание **breaking changes**",
Изменил описание

2021-03-25 17:12 UTC, poisonedvk commented on src/test/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManagerTest.kt
> +        Assert.assertFalse("В changelogs при мажорном обновлении должно быть описание **breaking changes**",
Изменил описание

2021-03-25 17:13 UTC, poisonedvk commented on src/test/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManagerTest.kt
> +    @Test
Кажется, что здесь достаточно локального теста.
Функционал на компонентах не тестировался. Надо подумать, как это лучше сделать

2021-03-25 18:54 UTC, layfe commented on src/test/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManagerTest.kt
> +    @Test
ок, но протестировать на либе надо. как можно сделать:
1) либо опубликуй в mavenLocal (локально ./gradlew clean build componentTest publishToMavenLocal)
2) либо используй опубликованный снапшот https://oss.sonatype.org/content/repositories/snapshots/ru/yoomoney/gradle/plugins/artifact-release-plugin/3.10.1-feature-breakingChangesCheckWhenMajor-SNAPSHOT/

3) подключи artifact-release-plugin (снапшотную версию) в libraries-project-plugin
4) подключи снапшотную версию libraries-project-plugin в любую либу с changelog (в project.gradle)
все, можно тестировать

2021-03-25 19:18 UTC, poisonedvk commented on src/test/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManagerTest.kt
> +    @Test
Обязательно проверю, спасибо!

2021-03-26 09:36 UTC, Xsires submitted a review, later dismissed

2021-03-26 09:36 UTC, Xsires commented on CHANGELOG.md
> +          ### NEXT_VERSION_DESCRIPTION_BEGIN
интересно не сломает ли это release plugin ) 
ведь теперь в есть 2 NEXT_VERSION_DESCRIPTION_END

2021-03-26 09:55 UTC, f0y commented on CHANGELOG.md
> +          ### NEXT_VERSION_DESCRIPTION_BEGIN
Ты про что?

2021-03-26 10:04 UTC, layfe commented on CHANGELOG.md
> +          ### NEXT_VERSION_DESCRIPTION_BEGIN
хороший поинт, думаю сломает)
о записи в changelog - в самом описании содержится маркер NEXT_VERSION_DESCRIPTION_BEGIN, может сломать

2021-03-26 10:15 UTC, poisonedvk commented on CHANGELOG.md
> +          ### NEXT_VERSION_DESCRIPTION_BEGIN
Давайте уберу, на всякий случай. Опишу в общих чертах. К тому же, эта инфа уже есть в README.MD

2021-03-26 10:47 UTC, poisonedvk commented on CHANGELOG.md
> +          ### NEXT_VERSION_DESCRIPTION_BEGIN
Изменил описание.

2021-03-26 10:50 UTC, f0y requested changes

2021-03-26 10:50 UTC, f0y commented on CHANGELOG.md
> +* **breaking changes** `В CheckChangeLogTask` добавлена проверка на то, что присутствует секция **breaking changes** при мажорном обновлении плагина.
А почему ты считаешь что это мажорное изменение? Просто же новая функциональность. Клиентам плагина ничего не надо делать.

2021-03-26 10:50 UTC, f0y commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManager.kt
> +    fun hasBreakingChangesWhenMajor(): Boolean {
Зачем такое сложное условие здесь оставлять. По сути метод называется isMajorAndIsBreakingChanges, что не говорит в его пользу. Надо здесь убрать проверку на major и перенести её ниже. 
Получится   `if (changelogManager.isMajor() && !changelogManager.hasBreakingChangesMarker ()) {`

2021-03-26 10:53 UTC, poisonedvk commented on src/test/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManagerTest.kt
> +    @Test
Работоспособность проверена на примере artifact-release-plugin.

Схематично выглядит так: artifact-release-plugin:3.10.1-feature-breakingChangesCheckWhenMajor-SNAPSHOT --> gradle-project-plugin:7.0.1-SNAPSHOT --> artifact-release-plugin

2021-03-26 10:53 UTC, poisonedvk commented on CHANGELOG.md
> +* **breaking changes** `В CheckChangeLogTask` добавлена проверка на то, что присутствует секция **breaking changes** при мажорном обновлении плагина.
Ну, можно минор, наверное. Меня смутило то, что если где-то не была указана секция **breaking changes**, то сборка падать будет

2021-03-26 10:55 UTC, poisonedvk commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManager.kt
> +    fun hasBreakingChangesWhenMajor(): Boolean {
В первой итерации у меня так и было) Но detekt стал ругаться, что в ChangelogManager слишком много методов. Я объединил два метода в один, показалось, что не критично.
Что думаешь? Детект повысить?

2021-03-26 11:12 UTC, f0y commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManager.kt
> +    fun hasBreakingChangesWhenMajor(): Boolean {
Возможно

2021-03-26 11:12 UTC, f0y commented on CHANGELOG.md
> +* **breaking changes** `В CheckChangeLogTask` добавлена проверка на то, что присутствует секция **breaking changes** при мажорном обновлении плагина.
Давай minor

2021-03-26 12:15 UTC, poisonedvk commented on CHANGELOG.md
> +* **breaking changes** `В CheckChangeLogTask` добавлена проверка на то, что присутствует секция **breaking changes** при мажорном обновлении плагина.
Изменил на MINOR

2021-03-26 12:15 UTC, poisonedvk commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/changelog/ChangelogManager.kt
> +    fun hasBreakingChangesWhenMajor(): Boolean {
Разделил на два метода с повышение static-analytics.properties

2021-03-26 12:16 UTC, layfe approved these changes

2021-03-26 12:25 UTC, f0y approved these changes

2021-03-26 12:30 UTC, merged