BACKEND-4766 artifact-release-plugin: ограничить список файлов, которые коммитятся при релизе
yoomoney-gradle-plugins/artifact-release-plugin pull request #20
Opened 2021-06-17 12:09 UTC by GSkoba

2021-06-17 14:10 UTC, f0y submitted a review, later dismissed

2021-06-17 14:10 UTC, f0y commented on CHANGELOG.md
> +* **breaking changes** artifact-release-plugin теперь коммитет только файлы
```suggestion
* **breaking changes** artifact-release-plugin теперь коммитит только файлы 
```

2021-06-17 14:15 UTC, cmygeHm commented on CHANGELOG.md
> +* **breaking changes** artifact-release-plugin теперь коммитет только файлы
```suggestion
* **breaking changes** artifact-release-plugin теперь коммитит только файлы 
```

2021-06-17 14:15 UTC, cmygeHm commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/ReleaseExtension.kt
> +     * Кастомный список файлов, которые попадут в комиит при вызове таски preRelease или release
```suggestion
     * Кастомный список файлов, которые попадут в коммит при вызове таски preRelease или release
```

2021-06-17 14:19 UTC, Xsires commented on CHANGELOG.md
> +              allowedFilesForCommit=['new-file.txt']
очень важно сделать так что бы паттерны работали /spec/**.yaml

2021-06-18 11:12 UTC, GSkoba commented on CHANGELOG.md
> +              allowedFilesForCommit=['new-file.txt']
Спасибо что подсветил данный момент, к сожелению [AddCommand.addFilepattern](http://archive.eclipse.org/jgit/docs/jgit-2.0.0.201206130900-r/apidocs/org/eclipse/jgit/api/AddCommand.html) не поддерживает `*`. 
```
filepattern - File to add content from. Also a leading directory name (e.g. dir to add dir/file1 and dir/file2) can be given to add all files in the directory, recursively. Fileglobs (e.g. *.c) are not yet supported.
```
Чтобы решить данную проблему добавил возможность прописывать regex.

2021-06-18 11:19 UTC, f0y requested changes

2021-06-18 11:19 UTC, f0y commented on CHANGELOG.md
> +              allowedFilesForCommit=['.txt']
здесь устаревшее название

2021-06-18 11:19 UTC, f0y commented on CHANGELOG.md
> +  `CHANGELOG.md`, `gradle.properties` и файлы обозначенные в `releaseSettings.allowedFilesForCommit`.
здесь тоже

2021-06-18 11:19 UTC, f0y commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/ReleaseExtension.kt
> +     * Кастомный список файлов, которые попадут в коммит при вызове таски preRelease или release
неактуальная дока

2021-06-18 11:19 UTC, f0y commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/git/GitManager.kt
> +     * @param allowedFilesForCommit кастомный список файлов, которые попадут в коммит
неактуальная дока

2021-06-18 11:19 UTC, f0y commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/git/GitManager.kt
> +     * @param allowedFilesForCommit кастомный список файлов, которые попадут в коммит
здесь тоже

2021-06-18 13:24 UTC, GSkoba commented
> Я не понимаю как у тебя .yaml сматчился new-file.yaml
@f0y @Xsires @ul8422 @cmygeHm 
Предлогаю обсудить данный момент. Подумал о том чтобы не делать строгий матч, а containsMatchIn чтобы имитировать поведение `*.yaml`. Если прописывать `.*yaml` или `.+yaml` все будет работать.

2021-06-21 08:58 UTC, ul8422 commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/ReleaseExtension.kt
> +     * Кастомный список файлов, которые попадут в коммит при вызове таски preRelease или release
А зачем  нам в конфигурации разрешенный список файлов для коммита?
Плагин затрагивает 2 файла: `gradle.properties` и `CHANGELOG.md`. Только эти 2 файла и нужно коммитить

2021-06-21 09:01 UTC, Xsires commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/ReleaseExtension.kt
> +     * Кастомный список файлов, которые попадут в коммит при вызове таски preRelease или release
помимо плагина file tree могут трогать другие таски, их изменения тоже нужно компитеть, а спеках мы ротирум версию в файле спецификации например

2021-06-21 09:09 UTC, ul8422 commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/ReleaseExtension.kt
> +     * Кастомный список файлов, которые попадут в коммит при вызове таски preRelease или release
немного смущает то, что мы хотим коммитить этим плагином файлы, измененные кем-то другим

2021-06-21 09:38 UTC, GSkoba commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/ReleaseExtension.kt
> +     * Кастомный список файлов, которые попадут в коммит при вызове таски preRelease или release
У плагина, есть возможность задавать набор кастомных `preReleaseTasks`, которые могут изменять дургие файлы. Есть такой вот пример https://bitbucket.yamoney.ru/projects/API/repos/wallet-api-specification/commits/93532cdb31674faafc186e6e9fe3a89b713f2195#specification/wallet-api.yaml

2021-06-21 09:54 UTC, GSkoba commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/git/GitManager.kt
> +     * @param allowedFilesForCommit кастомный список файлов, которые попадут в коммит
поправил, спасибо

2021-06-21 09:54 UTC, GSkoba commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/git/GitManager.kt
> +     * @param allowedFilesForCommit кастомный список файлов, которые попадут в коммит
поправил, спасибо

2021-06-21 09:54 UTC, GSkoba commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/ReleaseExtension.kt
> +     * Кастомный список файлов, которые попадут в коммит при вызове таски preRelease или release
поправил, спасибо

2021-06-21 09:54 UTC, GSkoba commented on CHANGELOG.md
> +  `CHANGELOG.md`, `gradle.properties` и файлы обозначенные в `releaseSettings.allowedFilesForCommit`.
поправил, спасибо

2021-06-21 09:54 UTC, GSkoba commented on CHANGELOG.md
> +              allowedFilesForCommit=['.txt']
поправил, спасибо

2021-06-21 09:55 UTC, GSkoba commented
Сделал строгий match на regex

2021-06-21 09:58 UTC, f0y approved these changes

2021-06-21 10:03 UTC, cmygeHm approved these changes

2021-06-21 10:23 UTC, hikarido commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/git/GitManager.kt
> +                    if (it.matches(fileName)) {
Это как раз полное соответствие регулярке?

2021-06-21 10:45 UTC, GSkoba commented on src/main/kotlin/ru/yoomoney/gradle/plugins/release/git/GitManager.kt
> +                    if (it.matches(fileName)) {
см https://github.com/yoomoney-gradle-plugins/artifact-release-plugin/pull/20#issuecomment-864900404

2021-06-21 10:57 UTC, f0y approved these changes

2021-06-21 11:52 UTC, merged